server.port=8080
spring.application.name=api-gateway

spring.cloud.gateway.server.webmvc.routes[0].id=rule-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/rules/**

spring.cloud.gateway.server.webmvc.routes[1].id=ingestion-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/ingestion/**

spring.cloud.gateway.server.webmvc.routes[2].id=error-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/errors/**

spring.cloud.gateway.server.webmvc.routes[3].id=valid-data-service
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8087
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/valid-records/**

spring.cloud.gateway.server.webmvc.routes[4].id=reporting-service
spring.cloud.gateway.server.webmvc.routes[4].uri=http://localhost:8088
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/quality/**